// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	auth "api-alta-dashboard/features/auth"

	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the ServiceInterface type
type AuthService struct {
	mock.Mock
}

// Login provides a mock function with given fields: input
func (_m *AuthService) Login(input auth.Core) (string, error) {
	ret := _m.Called(input)

	var r0 string
	if rf, ok := ret.Get(0).(func(auth.Core) string); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(auth.Core) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAuthService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthService(t mockConstructorTestingTNewAuthService) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
